version: '3.8'

services:
  flask-app-1:
    image: jordymeye/my-app:placeholder-v1
    container_name: flask-app-1
    ports:
      - "8001:8080"
    restart: always

  flask-app-2:
    image: jordymeye/my-app:placeholder-v2
    container_name: flask-app-2
    ports:
      - "8002:8080"
    restart: always